# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shopeasy_pb2 as shopeasy__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shopeasy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentGatewayStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessRefund = channel.unary_unary(
                '/shopeasy.PaymentGateway/ProcessRefund',
                request_serializer=shopeasy__pb2.RefundRequest.SerializeToString,
                response_deserializer=shopeasy__pb2.RefundResponse.FromString,
                _registered_method=True)


class PaymentGatewayServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessRefund(self, request, context):
        """Processes a refund securely
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessRefund': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessRefund,
                    request_deserializer=shopeasy__pb2.RefundRequest.FromString,
                    response_serializer=shopeasy__pb2.RefundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shopeasy.PaymentGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shopeasy.PaymentGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentGateway:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessRefund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shopeasy.PaymentGateway/ProcessRefund',
            shopeasy__pb2.RefundRequest.SerializeToString,
            shopeasy__pb2.RefundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
