# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shopeasy.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'shopeasy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshopeasy.proto\x12\x08shopeasy\"1\n\rRefundRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"9\n\x0eRefundResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t2T\n\x0ePaymentGateway\x12\x42\n\rProcessRefund\x12\x17.shopeasy.RefundRequest\x1a\x18.shopeasy.RefundResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shopeasy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFUNDREQUEST']._serialized_start=28
  _globals['_REFUNDREQUEST']._serialized_end=77
  _globals['_REFUNDRESPONSE']._serialized_start=79
  _globals['_REFUNDRESPONSE']._serialized_end=136
  _globals['_PAYMENTGATEWAY']._serialized_start=138
  _globals['_PAYMENTGATEWAY']._serialized_end=222
# @@protoc_insertion_point(module_scope)
