"""initial_migration_create_all_tables

Revision ID: 12a423fcb6ae
Revises: 
Create Date: 2025-11-24 13:30:24.401154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12a423fcb6ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_protocols',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_protocols_id'), 'action_protocols', ['id'], unique=True)
    op.create_index(op.f('ix_action_protocols_name'), 'action_protocols', ['name'], unique=True)
    op.create_table('api_auth_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_auth_types_id'), 'api_auth_types', ['id'], unique=True)
    op.create_index(op.f('ix_api_auth_types_name'), 'api_auth_types', ['name'], unique=True)
    op.create_table('chat_conversations',
    sa.Column('external_customer_id', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_customer_email'), 'chat_conversations', ['customer_email'], unique=False)
    op.create_index(op.f('ix_chat_conversations_external_customer_id'), 'chat_conversations', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_id'), 'chat_conversations', ['id'], unique=True)
    op.create_index(op.f('ix_chat_conversations_is_active'), 'chat_conversations', ['is_active'], unique=False)
    op.create_index(op.f('ix_chat_conversations_session_id'), 'chat_conversations', ['session_id'], unique=True)
    op.create_index(op.f('ix_chat_conversations_started_at'), 'chat_conversations', ['started_at'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('system_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_types_id'), 'system_types', ['id'], unique=True)
    op.create_index(op.f('ix_system_types_name'), 'system_types', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('agent_ratings',
    sa.Column('chat_conversation_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('response_type', sa.Enum('HELPFUL', 'NOT_HELPFUL', 'NEUTRAL', name='responsetype'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_ratings_chat_conversation_id'), 'agent_ratings', ['chat_conversation_id'], unique=True)
    op.create_index(op.f('ix_agent_ratings_external_customer_id'), 'agent_ratings', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_agent_ratings_id'), 'agent_ratings', ['id'], unique=True)
    op.create_table('api_authentications',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_primary_secret', sa.Text(), nullable=False),
    sa.Column('encrypted_secondary_secret', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_auth_type_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_auth_type_id'], ['api_auth_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_authentications_api_auth_type_id'), 'api_authentications', ['api_auth_type_id'], unique=False)
    op.create_index(op.f('ix_api_authentications_id'), 'api_authentications', ['id'], unique=True)
    op.create_index(op.f('ix_api_authentications_is_active'), 'api_authentications', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_authentications_name'), 'api_authentications', ['name'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('target_record_id', sa.UUID(), nullable=True),
    sa.Column('changed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=True)
    op.create_index(op.f('ix_audit_logs_target_record_id'), 'audit_logs', ['target_record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_table'), 'audit_logs', ['target_table'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'AGENT', 'SYSTEM', 'AI', name='sendertype'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('intent_detected', sa.String(length=255), nullable=True),
    sa.Column('entities_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_conversation_id'), 'chat_messages', ['chat_conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=True)
    op.create_table('tickets',
    sa.Column('ticket_type', sa.Enum('TECH', 'SUPPORT', name='tickettype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('ai_auto_created', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CLOSED', 'ESCALATED', 'CANCELED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'BILLING', 'GENERAL', 'COMPLAINT', 'FEATURE_REQUEST', name='ticketcategory'), nullable=True),
    sa.Column('sla_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('previous_assignee_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assignee_id'), 'tickets', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_customer_email'), 'tickets', ['customer_email'], unique=False)
    op.create_index(op.f('ix_tickets_external_customer_id'), 'tickets', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=True)
    op.create_index(op.f('ix_tickets_is_active'), 'tickets', ['is_active'], unique=False)
    op.create_index(op.f('ix_tickets_is_closed'), 'tickets', ['is_closed'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_sla_due_date'), 'tickets', ['sla_due_date'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_type'), 'tickets', ['ticket_type'], unique=False)
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('system_actions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint_url', sa.String(length=1000), nullable=False),
    sa.Column('request_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_type_id', sa.UUID(), nullable=False),
    sa.Column('action_protocol_id', sa.UUID(), nullable=False),
    sa.Column('api_authentication_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_protocol_id'], ['action_protocols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_authentication_id'], ['api_authentications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_type_id'], ['system_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_actions_action_protocol_id'), 'system_actions', ['action_protocol_id'], unique=False)
    op.create_index(op.f('ix_system_actions_api_authentication_id'), 'system_actions', ['api_authentication_id'], unique=False)
    op.create_index(op.f('ix_system_actions_id'), 'system_actions', ['id'], unique=True)
    op.create_index(op.f('ix_system_actions_is_active'), 'system_actions', ['is_active'], unique=False)
    op.create_index(op.f('ix_system_actions_name'), 'system_actions', ['name'], unique=False)
    op.create_index(op.f('ix_system_actions_system_type_id'), 'system_actions', ['system_type_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'AGENT', 'SYSTEM', 'AI', name='sendertype'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_id'), 'ticket_messages', ['id'], unique=True)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('action_execution_logs',
    sa.Column('system_action_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('chat_conversation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_action_id'], ['system_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_execution_logs_chat_conversation_id'), 'action_execution_logs', ['chat_conversation_id'], unique=False)
    op.create_index(op.f('ix_action_execution_logs_external_customer_id'), 'action_execution_logs', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_action_execution_logs_id'), 'action_execution_logs', ['id'], unique=True)
    op.create_index(op.f('ix_action_execution_logs_status'), 'action_execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_action_execution_logs_system_action_id'), 'action_execution_logs', ['system_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_execution_logs_system_action_id'), table_name='action_execution_logs')
    op.drop_index(op.f('ix_action_execution_logs_status'), table_name='action_execution_logs')
    op.drop_index(op.f('ix_action_execution_logs_id'), table_name='action_execution_logs')
    op.drop_index(op.f('ix_action_execution_logs_external_customer_id'), table_name='action_execution_logs')
    op.drop_index(op.f('ix_action_execution_logs_chat_conversation_id'), table_name='action_execution_logs')
    op.drop_table('action_execution_logs')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_system_actions_system_type_id'), table_name='system_actions')
    op.drop_index(op.f('ix_system_actions_name'), table_name='system_actions')
    op.drop_index(op.f('ix_system_actions_is_active'), table_name='system_actions')
    op.drop_index(op.f('ix_system_actions_id'), table_name='system_actions')
    op.drop_index(op.f('ix_system_actions_api_authentication_id'), table_name='system_actions')
    op.drop_index(op.f('ix_system_actions_action_protocol_id'), table_name='system_actions')
    op.drop_table('system_actions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_type'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sla_due_date'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_is_closed'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_is_active'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_external_customer_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_email'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_table'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_authentications_name'), table_name='api_authentications')
    op.drop_index(op.f('ix_api_authentications_is_active'), table_name='api_authentications')
    op.drop_index(op.f('ix_api_authentications_id'), table_name='api_authentications')
    op.drop_index(op.f('ix_api_authentications_api_auth_type_id'), table_name='api_authentications')
    op.drop_table('api_authentications')
    op.drop_index(op.f('ix_agent_ratings_id'), table_name='agent_ratings')
    op.drop_index(op.f('ix_agent_ratings_external_customer_id'), table_name='agent_ratings')
    op.drop_index(op.f('ix_agent_ratings_chat_conversation_id'), table_name='agent_ratings')
    op.drop_table('agent_ratings')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_types_name'), table_name='system_types')
    op.drop_index(op.f('ix_system_types_id'), table_name='system_types')
    op.drop_table('system_types')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_chat_conversations_started_at'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_session_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_is_active'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_external_customer_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_customer_email'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_api_auth_types_name'), table_name='api_auth_types')
    op.drop_index(op.f('ix_api_auth_types_id'), table_name='api_auth_types')
    op.drop_table('api_auth_types')
    op.drop_index(op.f('ix_action_protocols_name'), table_name='action_protocols')
    op.drop_index(op.f('ix_action_protocols_id'), table_name='action_protocols')
    op.drop_table('action_protocols')
    # ### end Alembic commands ###
