"""fix actionexecutionlog relationship

Revision ID: e094c955ea14
Revises: 3abacda9ae13
Create Date: 2025-11-19 21:38:52.388473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e094c955ea14'
down_revision: Union[str, Sequence[str], None] = '3abacda9ae13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_execution_logs', 'chat_conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-11-19 21:06:46.770801+02'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('action_execution_logs', 'chat_conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
